site_name: SUNRISE Documentation
site_author: Robert Bosch GmbH
site_description: This repository provides documentation and specifications for SUNRISE framework.
copyright: SUNRISE Documentation Â© 2025 by Robert Bosch GmbH is licensed under CC BY-SA 4.0.
repo_url: https://github.com/boschresearch/sunrise.documentation
nav:
  - Introduction: index.md
  - components.md
  - workflow.md
  - API Specifications: api_specification.md
  - Data Formats: dataformats.md
  - about.md
theme:
  name: readthedocs
  navigation_depth: 2
extra_css:
  - css/readthedocs_custom.css
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences
